version: "1.0.0"

services:
  database:
    container_name: backend-database
    image: postgres:latest
    environment:
      POSTGRES_USER: vial
      POSTGRES_PASSWORD: vial
      POSTGRES_DB: vial
    ports:
      - 5432:5432
  nodeserver:
    container_name: backend-api
    image: node:18.15.0
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    command: npm run dev
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - database
    ports:
      - 8080:8080
  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USERPOLLING=true
    volumes:
      - ./frontend:/usr/app/
